steps:
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}'
substitutions:
  _GOOGLE_API_KEY: 'AIzaSyCArKP2GlnCpc2Hl3A3qBkRK_e5Gv7qH6g'
'
